### ISSUE TITLE
Page hangs sometimes when an element has an invalid colour

### ISSUE THREAD

**Issue by l2wilson94** [l2wilson94/SandPond#14]
Instead, maybe it should just give a warning and carry on.

Or maybe, it should show an error at load-time.

I'm thinking a warning is fine.

**Comment by ajawsome4ev** [comment]
yeah a warning would work

**Comment by l2wilson94** [comment]
I realised this is actually an issue in SpaceTode code.

Moved to: https://github.com/l2wilson94/SpaceTode/issues/4

**Comment by l2wilson94** [comment]
Required a spacetode update. Now fixed: https://github.com/l2wilson94/SpaceTode/issues/4
